# Jose Arturo Villalobos A00818214
# Rodrigo Valencia
# Diseno de compiladores
# Cubo Semantico
#Creacion: 25 de Abril 2020
#Ultima modificacion: 27 Abril 2020

class CuboSemantico:
    def __init__(self):
        '''
        Diccionario que establece todas las posibles combinaciones que puede haber entre dos operandos para todos los tipos de datos que va a manejar el lenguaje COVID.
        
        Los tipos de datos que contiene COVID son:
            - Int
            - Float
            - Char
            - String
            - Dataframe

        (operando1, operando2, operador) : tipo de operando resultante

        Error: Type Mismatch
        
        '''

        self.diccionario = {
            #Int 
            ('int' , 'int' , '+' ) : 'int',
            ('int' , 'int' , '-' ) : 'int',
            ('int' , 'int' , '*' ) : 'int',
            ('int' , 'int' , '/' ) : 'float',
            ('int' , 'int' , '=' ) : 'int',
            ('int' , 'int' , '==' ) : 'bool',
            ('int' , 'int' , '<' ) : 'bool',
            ('int' , 'int' , '>' ) : 'bool',
            ('int' , 'int' , '<=' ) : 'bool',
            ('int' , 'int' , '>=' ) : 'bool',
            ('int' , 'int' , '!=' ) : 'bool',
            ('int' , 'int' , '|' ) : 'error',
            ('int' , 'int' , '&' ) : 'error',

            ('int' , 'float' , '+' ) : 'float',
            ('int' , 'float' , '-' ) : 'float',
            ('int' , 'float' , '*' ) : 'float',
            ('int' , 'float' , '/' ) : 'float',
            ('int' , 'float' , '=' ) : 'int', #Se redondea
            ('int' , 'float' , '==' ) : 'bool',
            ('int' , 'float' , '<' ) : 'bool',
            ('int' , 'float' , '>' ) : 'bool',
            ('int' , 'float' , '<=' ) : 'bool',
            ('int' , 'float' , '>=' ) : 'bool',
            ('int' , 'float' , '!=' ) : 'bool',
            ('int' , 'float' , '|' ) : 'error',
            ('int' , 'float' , '&' ) : 'error',

            ('int' , 'char' , '+' ) : 'error',
            ('int' , 'char' , '-' ) : 'error',
            ('int' , 'char' , '*' ) : 'error',
            ('int' , 'char' , '/' ) : 'error',
            ('int' , 'char' , '=' ) : 'error', 
            ('int' , 'char' , '==' ) : 'error',
            ('int' , 'char' , '<' ) : 'error',
            ('int' , 'char' , '>' ) : 'error',
            ('int' , 'char' , '<=' ) : 'error',
            ('int' , 'char' , '>=' ) : 'error',
            ('int' , 'char' , '!=' ) : 'error',
            ('int' , 'char' , '|' ) : 'error',
            ('int' , 'char' , '&' ) : 'error',
 
            ('int' , 'string' , '+' ) : 'error',
            ('int' , 'string' , '-' ) : 'error',
            ('int' , 'string' , '*' ) : 'error',
            ('int' , 'string' , '/' ) : 'error',
            ('int' , 'string' , '=' ) : 'error', 
            ('int' , 'string' , '==' ) : 'error',
            ('int' , 'string' , '<' ) : 'error',
            ('int' , 'string' , '>' ) : 'error',
            ('int' , 'string' , '<=' ) : 'error',
            ('int' , 'string' , '>=' ) : 'error',
            ('int' , 'string' , '!=' ) : 'error',
            ('int' , 'string' , '|' ) : 'error',
            ('int' , 'string' , '&' ) : 'error',

            ('int' , 'dataframe' , '+' ) : 'error',
            ('int' , 'dataframe' , '-' ) : 'error',
            ('int' , 'dataframe' , '*' ) : 'error',
            ('int' , 'dataframe' , '/' ) : 'error',
            ('int' , 'dataframe' , '=' ) : 'error', 
            ('int' , 'dataframe' , '==' ) : 'error',
            ('int' , 'dataframe' , '<' ) : 'error',
            ('int' , 'dataframe' , '>' ) : 'error',
            ('int' , 'dataframe' , '<=' ) : 'error',
            ('int' , 'dataframe' , '>=' ) : 'error',
            ('int' , 'dataframe' , '!=' ) : 'error',
            ('int' , 'dataframe' , '|' ) : 'error',
            ('int' , 'dataframe' , '&' ) : 'error',
            
            #Float 
            ('float' , 'int' , '+' ) : 'float',
            ('float' , 'int' , '-' ) : 'float',
            ('float' , 'int' , '*' ) : 'float',
            ('float' , 'int' , '/' ) : 'float',
            ('float' , 'int' , '=' ) : 'float', 
            ('float' , 'int' , '==' ) : 'bool',
            ('float' , 'int' , '<' ) : 'bool',
            ('float' , 'int' , '>' ) : 'bool',
            ('float' , 'int' , '<=' ) : 'bool',
            ('float' , 'int' , '>=' ) : 'bool',
            ('float' , 'int' , '!=' ) : 'bool',
            ('float' , 'int' , '|' ) : 'error',
            ('float' , 'int' , '&' ) : 'error',

            ('float' , 'float' , '+' ) : 'float',
            ('float' , 'float' , '-' ) : 'float',
            ('float' , 'float' , '*' ) : 'float',
            ('float' , 'float' , '/' ) : 'float',
            ('float' , 'float' , '=' ) : 'float', 
            ('float' , 'float' , '==' ) : 'bool',
            ('float' , 'float' , '<' ) : 'bool',
            ('float' , 'float' , '>' ) : 'bool',
            ('float' , 'float' , '<=' ) : 'bool',
            ('float' , 'float' , '>=' ) : 'bool',
            ('float' , 'float' , '!=' ) : 'bool',
            ('float' , 'float' , '|' ) : 'error',
            ('float' , 'float' , '&' ) : 'error',

            ('float' , 'char' , '+' ) : 'error',
            ('float' , 'char' , '-' ) : 'error',
            ('float' , 'char' , '*' ) : 'error',
            ('float' , 'char' , '/' ) : 'error',
            ('float' , 'char' , '=' ) : 'error', 
            ('float' , 'char' , '==' ) : 'error',
            ('float' , 'char' , '<' ) : 'error',
            ('float' , 'char' , '>' ) : 'error',
            ('float' , 'char' , '<=' ) : 'error',
            ('float' , 'char' , '>=' ) : 'error',
            ('float' , 'char' , '!=' ) : 'error',
            ('float' , 'char' , '|' ) : 'error',
            ('float' , 'char' , '&' ) : 'error',

            ('float' , 'string' , '+' ) : 'error',
            ('float' , 'string' , '-' ) : 'error',
            ('float' , 'string' , '*' ) : 'error',
            ('float' , 'string' , '/' ) : 'error',
            ('float' , 'string' , '=' ) : 'error', 
            ('float' , 'string' , '==' ) : 'error',
            ('float' , 'string' , '<' ) : 'error',
            ('float' , 'string' , '>' ) : 'error',
            ('float' , 'string' , '<=' ) : 'error',
            ('float' , 'string' , '>=' ) : 'error',
            ('float' , 'string' , '!=' ) : 'error',
            ('float' , 'string' , '|' ) : 'error',
            ('float' , 'string' , '&' ) : 'error',

            ('float' , 'dataframe' , '+' ) : 'error',
            ('float' , 'dataframe' , '-' ) : 'error',
            ('float' , 'dataframe' , '*' ) : 'error',
            ('float' , 'dataframe' , '/' ) : 'error',
            ('float' , 'dataframe' , '=' ) : 'error', 
            ('float' , 'dataframe' , '==' ) : 'error',
            ('float' , 'dataframe' , '<' ) : 'error',
            ('float' , 'dataframe' , '>' ) : 'error',
            ('float' , 'dataframe' , '<=' ) : 'error',
            ('float' , 'dataframe' , '>=' ) : 'error',
            ('float' , 'dataframe' , '!=' ) : 'error',
            ('float' , 'dataframe' , '|' ) : 'error',
            ('float' , 'dataframe' , '&' ) : 'error',

            #Char
            ('char' , 'int' , '+' ) : 'error',
            ('char' , 'int' , '-' ) : 'error',
            ('char' , 'int' , '*' ) : 'error',
            ('char' , 'int' , '/' ) : 'error',
            ('char' , 'int' , '=' ) : 'error', 
            ('char' , 'int' , '==' ) : 'error',
            ('char' , 'int' , '<' ) : 'error',
            ('char' , 'int' , '>' ) : 'error',
            ('char' , 'int' , '<=' ) : 'error',
            ('char' , 'int' , '>=' ) : 'error',
            ('char' , 'int' , '!=' ) : 'error',
            ('char' , 'int' , '|' ) : 'error',
            ('char' , 'int' , '&' ) : 'error',

            ('char' , 'float' , '+' ) : 'error',
            ('char' , 'float' , '-' ) : 'error',
            ('char' , 'float' , '*' ) : 'error',
            ('char' , 'float' , '/' ) : 'error',
            ('char' , 'float' , '=' ) : 'error', 
            ('char' , 'float' , '==' ) : 'error',
            ('char' , 'float' , '<' ) : 'error',
            ('char' , 'float' , '>' ) : 'error',
            ('char' , 'float' , '<=' ) : 'error',
            ('char' , 'float' , '>=' ) : 'error',
            ('char' , 'float' , '!=' ) : 'error',
            ('char' , 'float' , '|' ) : 'error',
            ('char' , 'float' , '&' ) : 'error',

            ('char' , 'char' , '+' ) : 'error',
            ('char' , 'char' , '-' ) : 'error',
            ('char' , 'char' , '*' ) : 'error',
            ('char' , 'char' , '/' ) : 'error',
            ('char' , 'char' , '=' ) : 'char', 
            ('char' , 'char' , '==' ) : 'bool',
            ('char' , 'char' , '<' ) : 'error',
            ('char' , 'char' , '>' ) : 'error',
            ('char' , 'char' , '<=' ) : 'error',
            ('char' , 'char' , '>=' ) : 'error',
            ('char' , 'char' , '!=' ) : 'bool',
            ('char' , 'char' , '|' ) : 'error',
            ('char' , 'char' , '&' ) : 'error',

            ('char' , 'string' , '+' ) : 'error',
            ('char' , 'string' , '-' ) : 'error',
            ('char' , 'string' , '*' ) : 'error',
            ('char' , 'string' , '/' ) : 'error',
            ('char' , 'string' , '=' ) : 'error', 
            ('char' , 'string' , '==' ) : 'bool',
            ('char' , 'string' , '<' ) : 'error',
            ('char' , 'string' , '>' ) : 'error',
            ('char' , 'string' , '<=' ) : 'error',
            ('char' , 'string' , '>=' ) : 'error',
            ('char' , 'string' , '!=' ) : 'bool',
            ('char' , 'string' , '|' ) : 'error',
            ('char' , 'string' , '&' ) : 'error',

            ('char' , 'dataframe' , '+' ) : 'error',
            ('char' , 'dataframe' , '-' ) : 'error',
            ('char' , 'dataframe' , '*' ) : 'error',
            ('char' , 'dataframe' , '/' ) : 'error',
            ('char' , 'dataframe' , '=' ) : 'error', 
            ('char' , 'dataframe' , '==' ) : 'error',
            ('char' , 'dataframe' , '<' ) : 'error',
            ('char' , 'dataframe' , '>' ) : 'error',
            ('char' , 'dataframe' , '<=' ) : 'error',
            ('char' , 'dataframe' , '>=' ) : 'error',
            ('char' , 'dataframe' , '!=' ) : 'error',
            ('char' , 'dataframe' , '|' ) : 'error',
            ('char' , 'dataframe' , '&' ) : 'error',

            #String
            ('string' , 'int' , '+' ) : 'error',
            ('string' , 'int' , '-' ) : 'error',
            ('string' , 'int' , '*' ) : 'error',
            ('string' , 'int' , '/' ) : 'error',
            ('string' , 'int' , '=' ) : 'error', 
            ('string' , 'int' , '==' ) : 'error',
            ('string' , 'int' , '<' ) : 'error',
            ('string' , 'int' , '>' ) : 'error',
            ('string' , 'int' , '<=' ) : 'error',
            ('string' , 'int' , '>=' ) : 'error',
            ('string' , 'int' , '!=' ) : 'error',
            ('string' , 'int' , '|' ) : 'error',
            ('string' , 'int' , '&' ) : 'error',

            ('string' , 'float' , '+' ) : 'error',
            ('string' , 'float' , '-' ) : 'error',
            ('string' , 'float' , '*' ) : 'error',
            ('string' , 'float' , '/' ) : 'error',
            ('string' , 'float' , '=' ) : 'error', 
            ('string' , 'float' , '==' ) : 'error',
            ('string' , 'float' , '<' ) : 'error',
            ('string' , 'float' , '>' ) : 'error',
            ('string' , 'float' , '<=' ) : 'error',
            ('string' , 'float' , '>=' ) : 'error',
            ('string' , 'float' , '!=' ) : 'error',
            ('string' , 'float' , '|' ) : 'error',
            ('string' , 'float' , '&' ) : 'error',

            ('string' , 'char' , '+' ) : 'error',
            ('string' , 'char' , '-' ) : 'error',
            ('string' , 'char' , '*' ) : 'error',
            ('string' , 'char' , '/' ) : 'error',
            ('string' , 'char' , '=' ) : 'error', 
            ('string' , 'char' , '==' ) : 'bool',
            ('string' , 'char' , '<' ) : 'error',
            ('string' , 'char' , '>' ) : 'error',
            ('string' , 'char' , '<=' ) : 'error',
            ('string' , 'char' , '>=' ) : 'error',
            ('string' , 'char' , '!=' ) : 'bool',
            ('string' , 'char' , '|' ) : 'error',
            ('string' , 'char' , '&' ) : 'error',

            ('string' , 'string' , '+' ) : 'error',
            ('string' , 'string' , '-' ) : 'error',
            ('string' , 'string' , '*' ) : 'error',
            ('string' , 'string' , '/' ) : 'error',
            ('string' , 'string' , '=' ) : 'error', 
            ('string' , 'string' , '==' ) : 'bool',
            ('string' , 'string' , '<' ) : 'error',
            ('string' , 'string' , '>' ) : 'error',
            ('string' , 'string' , '<=' ) : 'error',
            ('string' , 'string' , '>=' ) : 'error',
            ('string' , 'string' , '!=' ) : 'bool',
            ('string' , 'string' , '|' ) : 'error',
            ('string' , 'string' , '&' ) : 'error',

            ('string' , 'dataframe' , '+' ) : 'error',
            ('string' , 'dataframe' , '-' ) : 'error',
            ('string' , 'dataframe' , '*' ) : 'error',
            ('string' , 'dataframe' , '/' ) : 'error',
            ('string' , 'dataframe' , '=' ) : 'error', 
            ('string' , 'dataframe' , '==' ) : 'error',
            ('string' , 'dataframe' , '<' ) : 'error',
            ('string' , 'dataframe' , '>' ) : 'error',
            ('string' , 'dataframe' , '<=' ) : 'error',
            ('string' , 'dataframe' , '>=' ) : 'error',
            ('string' , 'dataframe' , '!=' ) : 'error',
            ('string' , 'dataframe' , '|' ) : 'error',
            ('string' , 'dataframe' , '&' ) : 'error',

            #Dataframe
            ('dataframe' , 'int' , '+' ) : 'error',
            ('dataframe' , 'int' , '-' ) : 'error',
            ('dataframe' , 'int' , '*' ) : 'error',
            ('dataframe' , 'int' , '/' ) : 'error',
            ('dataframe' , 'int' , '=' ) : 'error', 
            ('dataframe' , 'int' , '==' ) : 'error',
            ('dataframe' , 'int' , '<' ) : 'error',
            ('dataframe' , 'int' , '>' ) : 'error',
            ('dataframe' , 'int' , '<=' ) : 'error',
            ('dataframe' , 'int' , '>=' ) : 'error',
            ('dataframe' , 'int' , '!=' ) : 'error',
            ('dataframe' , 'int' , '|' ) : 'error',
            ('dataframe' , 'int' , '&' ) : 'error',

            ('dataframe' , 'float' , '+' ) : 'error',
            ('dataframe' , 'float' , '-' ) : 'error',
            ('dataframe' , 'float' , '*' ) : 'error',
            ('dataframe' , 'float' , '/' ) : 'error',
            ('dataframe' , 'float' , '=' ) : 'error', 
            ('dataframe' , 'float' , '==' ) : 'error',
            ('dataframe' , 'float' , '<' ) : 'error',
            ('dataframe' , 'float' , '>' ) : 'error',
            ('dataframe' , 'float' , '<=' ) : 'error',
            ('dataframe' , 'float' , '>=' ) : 'error',
            ('dataframe' , 'float' , '!=' ) : 'error',
            ('dataframe' , 'float' , '|' ) : 'error',
            ('dataframe' , 'float' , '&' ) : 'error',

            ('dataframe' , 'char' , '+' ) : 'error',
            ('dataframe' , 'char' , '-' ) : 'error',
            ('dataframe' , 'char' , '*' ) : 'error',
            ('dataframe' , 'char' , '/' ) : 'error',
            ('dataframe' , 'char' , '=' ) : 'error', 
            ('dataframe' , 'char' , '==' ) : 'error',
            ('dataframe' , 'char' , '<' ) : 'error',
            ('dataframe' , 'char' , '>' ) : 'error',
            ('dataframe' , 'char' , '<=' ) : 'error',
            ('dataframe' , 'char' , '>=' ) : 'error',
            ('dataframe' , 'char' , '!=' ) : 'error',
            ('dataframe' , 'char' , '|' ) : 'error',
            ('dataframe' , 'char' , '&' ) : 'error',

            ('dataframe' , 'string' , '+' ) : 'error',
            ('dataframe' , 'string' , '-' ) : 'error',
            ('dataframe' , 'string' , '*' ) : 'error',
            ('dataframe' , 'string' , '/' ) : 'error',
            ('dataframe' , 'string' , '=' ) : 'error', 
            ('dataframe' , 'string' , '==' ) : 'error',
            ('dataframe' , 'string' , '<' ) : 'error',
            ('dataframe' , 'string' , '>' ) : 'error',
            ('dataframe' , 'string' , '<=' ) : 'error',
            ('dataframe' , 'string' , '>=' ) : 'error',
            ('dataframe' , 'string' , '!=' ) : 'error',
            ('dataframe' , 'string' , '|' ) : 'error',
            ('dataframe' , 'string' , '&' ) : 'error',

            ('dataframe' , 'dataframe' , '+' ) : 'error',
            ('dataframe' , 'dataframe' , '-' ) : 'error',
            ('dataframe' , 'dataframe' , '*' ) : 'error',
            ('dataframe' , 'dataframe' , '/' ) : 'error',
            ('dataframe' , 'dataframe' , '=' ) : 'dataframe', 
            ('dataframe' , 'dataframe' , '==' ) : 'error',
            ('dataframe' , 'dataframe' , '<' ) : 'error',
            ('dataframe' , 'dataframe' , '>' ) : 'error',
            ('dataframe' , 'dataframe' , '<=' ) : 'error',
            ('dataframe' , 'dataframe' , '>=' ) : 'error',
            ('dataframe' , 'dataframe' , '!=' ) : 'error',
            ('dataframe' , 'dataframe' , '|' ) : 'error',
            ('dataframe' , 'dataframe' , '&' ) : 'error',

            ('lee', 'int', '') : 'char',
            ('lee', 'float', '') : 'char',
            ('lee', 'char', '') : 'char',
            ('lee', 'string', '') : 'char',
            ('lee', 'dataframe', '') : 'char',

            ('escribe', 'int', '') : 'char',
            ('escribe', 'float', '') : 'char',
            ('escribe', 'char', '') : 'char',
            ('escribe', 'string', '') : 'char',
            ('escribe', 'dataframe', '') : 'char'

            
        }

    '''
    Funcion para obtener el tipo resultado de la operacion entre dos operandos
    '''
    def getType(self, operando1, operando2, operador):

        # if 'error' not in self.diccionario[operando1, operando2, operador]:
        #     return self.diccionario[operando1, operando2, operador]
        # else:
        #     raise TypeError(f"Type Mismatch: No puede aplicarse el operador '{operador}' a los tipos '{operando1}' y '{operando2}' ")
        return self.diccionario[operando1, operando2, operador]

    